name: ' Deploy Reference Documentation'

on:
  workflow_dispatch:

permissions:
  actions: read
  contents: read
  id-token: write
  pages: write

defaults:
  run:
    shell: pwsh

env:
  ALGoOrgSettings: ${{ vars.ALGoOrgSettings }}
  ALGoRepoSettings: ${{ vars.ALGoRepoSettings }}

jobs:
  DeployALDoc:
    runs-on: [ ubuntu-latest ]
    name: Deploy Reference Documentation
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Initialize the workflow
        id: init
        uses: Freddy-DK/AL-Go/Actions/WorkflowInitialize@07a22c28bf4ef6863e617b2340163a1a612aa07e
        with:
          shell: pwsh

      - name: Read settings
        uses: Freddy-DK/AL-Go/Actions/ReadSettings@07a22c28bf4ef6863e617b2340163a1a612aa07e
        with:
          shell: pwsh

      - name: Determine ArtifactUrl
        id: determineArtifactUrl
        uses: Freddy-DK/AL-Go/Actions/DetermineArtifactUrl@07a22c28bf4ef6863e617b2340163a1a612aa07e
        with:
          shell: pwsh

      - name: Determine Deployment Environments
        id: DetermineDeploymentEnvironments
        uses: Freddy-DK/AL-Go/Actions/DetermineDeploymentEnvironments@07a22c28bf4ef6863e617b2340163a1a612aa07e
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          shell: pwsh
          getEnvironments: 'github-pages'
          type: 'Publish'

      - name: Setup Pages
        if: steps.DetermineDeploymentEnvironments.outputs.deployALDocArtifact == 1
        uses: actions/configure-pages@45bfe0192ca1faeb007ade9deae92b16b8254a0d # v6.0.0

      - name: Build Reference Documentation
        uses: Freddy-DK/AL-Go/Actions/BuildReferenceDocumentation@07a22c28bf4ef6863e617b2340163a1a612aa07e
        with:
          shell: pwsh
          artifacts: 'latest'
          artifactUrl: ${{ env.artifact }}

      - name: Upload pages artifact
        uses: actions/upload-pages-artifact@fc324d3547104276b827a68afc52ff2a11cc49c9 # v5.0.0
        with:
          path: ".aldoc/_site/"

      - name: Deploy to GitHub Pages
        if: steps.DetermineDeploymentEnvironments.outputs.deployALDocArtifact == 1
        id: deployment
        uses: actions/deploy-pages@368f82528645a54fb793d4d04e342629a3f51346 # v5.0.1

      - name: Finalize the workflow
        if: always()
        uses: Freddy-DK/AL-Go/Actions/WorkflowPostProcess@07a22c28bf4ef6863e617b2340163a1a612aa07e
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          shell: pwsh
          telemetryScopeJson: ${{ steps.init.outputs.telemetryScopeJson }}
          currentJobContext: ${{ toJson(job) }}
